<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="122685" started-at="2020-07-09T07:08:45Z" finished-at="2020-07-09T07:10:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="122685" started-at="2020-07-09T07:08:45Z" finished-at="2020-07-09T07:10:47Z">
      <class name="testcases.Test_Continue_Watching">
        <test-method status="PASS" signature="set()[pri:0, instance:testcases.Test_Continue_Watching@410ae9a3]" name="set" is-config="true" duration-ms="2377" started-at="2020-07-09T14:08:46Z" finished-at="2020-07-09T14:08:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="FAIL" signature="continue_watching_from_exclusive(java.lang.String, java.lang.String)[pri:0, instance:testcases.Test_Continue_Watching@410ae9a3]" name="continue_watching_from_exclusive" duration-ms="112905" started-at="2020-07-09T14:08:48Z" data-provider="continue_watching" finished-at="2020-07-09T14:10:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dikakoko04@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dikakoko]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at object.Button.byClassSize(Button.java:182)
	at testcases.Test_Continue_Watching.continue_watching_from_exclusive(Test_Continue_Watching.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- continue_watching_from_exclusive -->
        <test-method status="PASS" signature="done(org.testng.ITestResult)[pri:0, instance:testcases.Test_Continue_Watching@410ae9a3]" name="done" is-config="true" duration-ms="6050" started-at="2020-07-09T14:10:41Z" finished-at="2020-07-09T14:10:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=continue_watching_from_exclusive status=FAILURE method=Test_Continue_Watching.continue_watching_from_exclusive(java.lang.String, java.lang.String)[pri:0, instance:testcases.Test_Continue_Watching@410ae9a3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- done -->
      </class> <!-- testcases.Test_Continue_Watching -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
